MOZGAMAR/Controllers/AdminController.cs
using Domain;
using MOZGAMAR.Models;
using EFDBAcess.Repository;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MOZGAMAR.Controllers
{
    public class AdminController : Controller
    {

        public GenericUnitOfWork _unitOfWork = new GenericUnitOfWork();

        public List<SelectListItem> GetCategoty()
        {
            List<SelectListItem> selectListItems = new List<SelectListItem>();

            foreach (var item in _unitOfWork.GetRepositoryInstance<Category>().GetAllRecords().Where(x => x.IsActive == true))
            {
                selectListItems.Add(new SelectListItem { Value = item.CategoryId.ToString(), Text = item.Name });
            }

            return selectListItems;
        }

        // GET: Admin
        public ActionResult Dashboard()
        {
            return View();
        }



        #region Category
        public ActionResult Category()
        {
            List<Category> allcategories = _unitOfWork.GetRepositoryInstance<Category>().GetAllRecordsIQueryable().Where(x => x.IsActive == true).ToList();
            return View(allcategories);
        }
        public ActionResult AddCategory()
        {
            return UpdateOrSaveCategory(0);
        }
        public ActionResult UpdateOrSaveCategory(int Id)
        {
            CategoryDetails cd;
            if (Id != 0 & Id > 0)
            {
                cd = JsonConvert.DeserializeObject<CategoryDetails>(JsonConvert.SerializeObject(_unitOfWork.GetRepositoryInstance<Category>().GetFirstOrDefault(Id)));
            }
            else
            {
                cd = new CategoryDetails();
            }

            return View("UpdateCategory", cd);

        }
        [HttpPost]
        public ActionResult UpdateOrSaveCategory(Category category)
        {
            if (category.CategoryId > 0)
            {
                category.IsActive = true;
                _unitOfWork.GetRepositoryInstance<Category>().Update(category);
            }
            else
            {
                _unitOfWork.GetRepositoryInstance<Category>().Add(category);
            }

            return RedirectToAction("Category");
        }
        #endregion


        #region Product
        public ActionResult Product()
        {
            return View(_unitOfWork.GetRepositoryInstance<Product>().GetProduct());
        }
        public ActionResult CreateProduct()
        {
            return UpdateProduct(0);
        }
        public ActionResult UpdateProduct(int id)
        {
            ViewBag.GetCategoty = GetCategoty();

            Product product;
            if (id == 0)
            {
                product = new Product();
            }
            else
            {
                product = _unitOfWork.GetRepositoryInstance<Product>().GetFirstOrDefault(id);
            }

            return View("UpdateProduct", product);
        }
        [HttpPost]
        public ActionResult UpdateOrSaveProduct(Product product, HttpPostedFileBase fileBase)
        {
            if (ModelState.IsValid)
            {
                if (product.ProductImage == null)
                {
                    string pic = null;
                    if (fileBase != null)
                    {
                        pic = System.IO.Path.GetFileName(fileBase.FileName);
                        string paht = System.IO.Path.Combine(Server.MapPath("~/ProducIMG/"), pic);

                        fileBase.SaveAs(paht);
                    }
                    product.ProductImage = pic;
                }
              
                if (product.ProductId > 0)
                {
                    product.ModifiedDate = DateTime.Now;
                    _unitOfWork.GetRepositoryInstance<Product>().Update(product);
                }
                else
                {
                    product.CreatedDate = DateTime.Now;
                    _unitOfWork.GetRepositoryInstance<Product>().Add(product);
                }

                return RedirectToAction("Product");
            }
            else
            {
                return RedirectToAction("CreateProduct", product);
            }


        }
        #endregion


    }
}

MOZGAMAR/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain;
using EFDBAcess;

namespace MOZGAMAR.Controllers
{
    public class RequestsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Requests
        public ActionResult Index()
        {
            var requests = db.Requests.Include(r => r.Category);
            return View(requests.ToList());
        }

        // GET: Requests/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Request request = db.Requests.Find(id);
            if (request == null)
            {
                return HttpNotFound();
            }
            return View(request);
        }

        // GET: Requests/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Category, "CategoryId", "Name");
            return View();
        }

        // POST: Requests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Request request, HttpPostedFileBase fileBase)
        {
            if (ModelState.IsValid)
            { 
                    if (fileBase != null)
                    {
                      var  pic = System.IO.Path.GetFileName(fileBase.FileName);
                        string paht = System.IO.Path.Combine(Server.MapPath("~/Images/Requests/"), pic);
                        fileBase.SaveAs(paht);
                    request.RequestImage = pic;
                }
                  
                


                db.Requests.Add(request);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Category, "CategoryId", "Name", request.CategoryId);
            return View(request);
        }

        // GET: Requests/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Request request = db.Requests.Find(id);
            if (request == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Category, "CategoryId", "Name", request.CategoryId);
            return View(request);
        }

        // POST: Requests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "requestId,Name,Brand,InitialPrice,FinalPrice,Description,CategoryId")] Request request)
        {
            if (ModelState.IsValid)
            {
                db.Entry(request).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Category, "CategoryId", "Name", request.CategoryId);
            return View(request);
        }

        // GET: Requests/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Request request = db.Requests.Find(id);
            if (request == null)
            {
                return HttpNotFound();
            }
            return View(request);
        }

        // POST: Requests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Request request = db.Requests.Find(id);
            db.Requests.Remove(request);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MOZGAMAR/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!-- Bootstrap core CSS-->

    <link href="~/AdminStyleView/vendor/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <!-- Custom fonts for this template-->
    <link href="~/AdminStyleView/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <!-- Page level plugin CSS-->
    <link href="~/AdminStyleView/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <!-- Custom styles for this template--> 
    <link href="~/AdminStyleView/css/sb-admin.css" rel="stylesheet">
</head>
 
<body id="page-top" >
    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
        <a class="navbar-brand mr-1" href="~/Admin/Dashboard">MꙨZ GAMER</a>
        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>
        <!-- Navbar Search -->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
        <!-- Navbar -->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-bell fa-fw"></i>
                    <span class="badge badge-danger">9+</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item dropdown no-arrow mx-1">
                <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-envelope fa-fw"></i>
                    <span class="badge badge-danger">7</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-circle fa-fw"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Settings</a>
                    <a class="dropdown-item" href="#">Activity Log</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="sidebar navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="~/Home/Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Voltar para o site</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="~/Admin/Category">
                    <i class="fas fa-fw fa-boxes"></i>    
                    <span>
                        Categorias
                    </span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="~/Admin/Product"> 
                    <i class="fas fa-fw fa-keyboard-o"></i>
                    <span>Produtos</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="tables.html">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Encomendas</span>
                </a>
            </li>



        </ul>
        <div id="content-wrapper">

            <!-- Icon Cards-->
            @RenderBody()




            <!-- /.container-fluid -->
            <!-- Sticky Footer -->
            <footer class="sticky-footer">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright © MOZ GAMER </span>
                    </div>
                </div>
            </footer>
        </div>
        <!-- /.content-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>


</body>

</html>


<!-- Bootstrap core JavaScript-->
<script src="~/AdminStyleView/vendor/jquery/jquery.min.js"></script>
<script src="~/AdminStyleView/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="~/AdminStyleView/vendor/jquery-easing/jquery.easing.min.js"></script>
<!-- Page level plugin JavaScript-->
<script src="~/AdminStyleView/vendor/chart.js/Chart.min.js"></script>
<script src="~/AdminStyleView/vendor/datatables/jquery.dataTables.js"></script>
<script src="~/AdminStyleView/vendor/datatables/dataTables.bootstrap4.js"></script>
<!-- Custom scripts for all pages-->
<script src="~/AdminStyleView/js/sb-admin.min.js"></script>
<!-- Demo scripts for this page-->
<script src="~/AdminStyleView/js/demo/datatables-demo.js"></script>
<script src="~/AdminStyleView/js/demo/chart-area-demo.js"></script>

MOZGAMAR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MꙨZ GAMER </title>
    @*@Styles.Render("~/Content/css")*@
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/MyMainLayOut.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-6">
                <div class="logo">
                    <h1>MꙨZ G<label style="color:firebrick">A</label>MER</h1>
                    <p>loja online: versão 2.0</p>
                </div>
            </div>

            <div class="col-md-6 col-sm-6 col-xs-6">


                @*<li>
                <div class="hidden-xs">
                    <h4>Ligue:</h4>
                    <p>+258 84 822 0 187</p>
                </div>

                <div class="visible-xs">

                    <p>848220187</p>
                </div>
                 </li>*@
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">                        
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">Cadastrar<b class="caret"></b></a>
                        <ul class="dropdown-menu ">
                            <li><a href="@Url.Action("Product","Admin")">Venda<i class="pull-right fas fa-user-circle fa-fw"></i>  </a></li>
                            <li><a href="@Url.Action("Index","Requests")">Pedido<i class="pull-right fa fa-times"></i>  </a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">Carinho <b class="caret"></b></a>
                        <ul class="dropdown-menu ">
                            @if (Session["Mycart"] != null)
                            {
                                foreach (var item in (List<Domain.ProductItem>)Session["Mycart"])
                                {
                                    <li><a href="@Url.Action("RemoveFromMyCart","Home", new { @id = item.Product.ProductId})"> @item.Product.Name (@item.QuantityOfProductItem)  <i class="pull-right fa fa-times"></i>  </a></li>



                                }
                            }

                            <li class="divider"></li>
                            <li><a href="#">IT</a></li>
                        </ul>
                    </li>
                </ul>


            </div>

            <div class="row">
                <div class="col-md-12 ">
                    <div class="nav-menus">
                        <ul class="nav nav-pills">
                            <li class="active"><a style="border-radius:initial" href="~/Home/Index">Home</a></li>
                            <li><a style="border-radius:initial" >Pedidos</a></li>
                            <li><a style="border-radius:initial" href="~/Requests/Index">CONSOLA</a></li>
                            <li><a style="border-radius:initial" href="#">PERIFÉRICOS</a></li>
                        </ul>
                    </div>
                </div>
            </div>


            @RenderBody()
            <hr />
            <footer>
            <div class="row">
                <div class="col-md-12 copyright">

                    <div class="col-md-6 col-sm-6 copyright-left">
                        <p>&copy; @DateTime.Now.Year - MꙨZ GAMER  | All right reserved.</p>
                    </div>

                    <div class="col-md-6 col-sm-6 copyright-right">

                        <ul class="list-unstyled list-social">
                            <li><a href="#" target="_blank"><i class="fa fa-facebook-square"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>

                        </ul>
                    </div>
                </div>
            </div>

        </footer>
        
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MOZGAMAR/Views/Shared/_ZoomProduct.cshtml
@model Domain.Product

@{
    Layout = null;
}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="~/zoomproduct/dist/style.css">

<div class="wrapper">
    <div class="left">
        <img src="~/ProducIMG/@Model.ProductImage" />
    </div>
    <div class="right">
        <div class="inner">
            <img src="~/ProducIMG/@Model.ProductImage" />
        </div>
    </div>
</div>

<!-- partial -->
<script src="~/zoomproduct/dist/script.js"></script>